// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package database

import (
	"context"
	"fmt"
	"slices"
	"testing"
	"time"

	"github.com/glebarez/sqlite"
	"github.com/google/go-cmp/cmp"
	"google.golang.org/genai"
	"gorm.io/gorm"

	"google.golang.org/adk/v2/platform"
	"google.golang.org/adk/v2/session"
	"google.golang.org/adk/v2/session/sessiontestsuite"
)

func Test_databaseService(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true}
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return emptyService(t)
	})
}

func Test_databaseService_CreateUsesProviders(t *testing.T) {
	fixedTime := time.Date(2024, time.January, 2, 3, 4, 5, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	ctx = platform.WithUUIDProvider(ctx, func() string { return "fixed-session-id" })

	s := emptyService(t)
	resp, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if got := resp.Session.ID(); got != "fixed-session-id" {
		t.Errorf("autogenerated session ID = %q, want provider value %q", got, "fixed-session-id")
	}
	if got := resp.Session.LastUpdateTime(); !got.Equal(fixedTime) {
		t.Errorf("LastUpdateTime() = %v, want provider value %v", got, fixedTime)
	}
}

// TestDatabaseService_AppendEvent_WorkflowFieldsRoundTrip guards that
// the storage layer serializes/deserializes the workflow event fields
// (NodeInfo, RequestedInput, Routes, IsolationScope); dropping them
// breaks HITL resume and scope-isolated history.
func TestDatabaseService_AppendEvent_WorkflowFieldsRoundTrip(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	created, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	event := &session.Event{
		ID:             "wf_event",
		Author:         "agent",
		NodeInfo:       &session.NodeInfo{Path: "ask_name"},
		RequestedInput: &session.RequestInput{InterruptID: "ask_name", Message: "What's your name?"},
		Routes:         []string{"route_a"},
		IsolationScope: "task-1",
	}
	if err := s.AppendEvent(ctx, created.Session, event); err != nil {
		t.Fatalf("AppendEvent: %v", err)
	}

	got, err := s.Get(ctx, &session.GetRequest{AppName: "app", UserID: "user", SessionID: created.Session.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	evs := got.Session.Events()
	if evs.Len() != 1 {
		t.Fatalf("got %d events, want 1", evs.Len())
	}
	ev := evs.At(0)
	if ev.NodeInfo == nil || ev.NodeInfo.Path != "ask_name" {
		t.Errorf("NodeInfo not persisted: %#v", ev.NodeInfo)
	}
	if ev.RequestedInput == nil || ev.RequestedInput.InterruptID != "ask_name" {
		t.Errorf("RequestedInput not persisted: %#v", ev.RequestedInput)
	}
	if len(ev.Routes) != 1 || ev.Routes[0] != "route_a" {
		t.Errorf("Routes not persisted: %#v", ev.Routes)
	}
	if ev.IsolationScope != "task-1" {
		t.Errorf("IsolationScope not persisted: got %q, want %q", ev.IsolationScope, "task-1")
	}
}

func emptyService(t *testing.T) *databaseService {
	t.Helper()
	gormConfig := &gorm.Config{
		PrepareStmt: true,
	}

	service, err := NewSessionService(sqlite.Open("file::memory:?cache=shared"), gormConfig)
	if err != nil {
		t.Fatalf("Failed to create session service: %v", err)
	}
	dbservice, ok := service.(*databaseService)
	if !ok {
		t.Fatalf("invalid session service type")
	}

	err = AutoMigrate(service)
	if err != nil {
		t.Fatalf("Failed to AutoMigrate db: %v", err)
	}

	t.Cleanup(func() {
		t.Log("CLEANUP: Deleting all rows from tables...")

		// Define models in Child-to-Parent order
		modelsToDelete := []any{
			&storageEvent{}, // Child-most
			&storageSession{},
			&storageUserState{},
			&storageAppState{}, // Parent-most
		}

		for _, model := range modelsToDelete {
			// GORM statement parser to get table names
			stmt := &gorm.Statement{DB: dbservice.db}
			// Parse the model to get its table name
			if err := stmt.Parse(model); err != nil {
				t.Errorf("Failed to parse model schema for cleanup: %v", err)
				continue
			}
			tableName := stmt.Table

			// Exec with "WHERE true" instead of gorm.Delete()
			// satisfies Spanner's requirement for a WHERE clause.
			if err := dbservice.db.Exec(`DELETE FROM ` + tableName + ` WHERE true`).Error; err != nil {
				t.Errorf("Failed to delete from table %s: %v", tableName, err)
			}
		}
		sqlDB, err := dbservice.db.DB()
		if err != nil {
			t.Errorf("Failed to get underlying *sql.DB: %v", err)
			return
		}
		if err := sqlDB.Close(); err != nil {
			t.Errorf("Failed to close database connection: %v", err)
		}
	})

	return dbservice
}

func TestDatabaseService_AppendEvent_PreservesInputEventTempState(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	createResp, err := s.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}

	if err := s.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// Verify that the input event pointer's StateDelta map was not mutated in place.
	if _, exists := event.Actions.StateDelta["temp:k1"]; !exists {
		t.Errorf("expected temp:k1 to be preserved on input event after AppendEvent, but it was removed: %v", event.Actions.StateDelta)
	}
	if event.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk to remain in input event, got: %v", event.Actions.StateDelta)
	}

	// Verify that the stored event in the session has temp keys stripped.
	var storedEvent *session.Event
	for ev := range createResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("expected temp:k1 to be stripped from stored event, but it still exists: %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

// TestEventsSharingATimestampComeBackInAStableOrder pins that a tie does not
// flip between reads.
//
// Timestamps are truncated to microseconds on write, so two events in one tick
// are ordinary. The query fetches DESC so a limit takes the most recent and
// then reverses, and without a tiebreak SQLite's stable sort hands ties back in
// reverse insertion order, differently from how they went in. Compaction reads
// this order to decide what a summary stands for, so a pair that swaps lets a
// record cover an event nothing summarized.
func TestEventsSharingATimestampComeBackInAStableOrder(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	svc := emptyService(t)
	const appName, userID = "app", "user"
	created, err := svc.Create(ctx, &session.CreateRequest{AppName: appName, UserID: userID})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	sess := created.Session

	// Six events on one instant, appended in a known order.
	ts := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	var want []string
	for i := range 6 {
		ev := session.NewEvent(ctx, "inv1")
		ev.Author = "author"
		ev.Timestamp = ts
		ev.LLMResponse.Content = genai.NewContentFromText(fmt.Sprintf("event %d", i), genai.RoleUser)
		if err := svc.AppendEvent(ctx, sess, ev); err != nil {
			t.Fatalf("AppendEvent() error = %v", err)
		}
		want = append(want, ev.ID)
	}

	read := func() []string {
		got, err := svc.Get(ctx, &session.GetRequest{AppName: appName, UserID: userID, SessionID: sess.ID()})
		if err != nil {
			t.Fatalf("Get() error = %v", err)
		}
		var ids []string
		for ev := range got.Session.Events().All() {
			ids = append(ids, ev.ID)
		}
		return ids
	}

	first := read()
	// Stable across reads is the property compaction depends on.
	for range 5 {
		if diff := cmp.Diff(first, read()); diff != "" {
			t.Fatalf("the order of tied events changed between reads (-first +later):\n%s", diff)
		}
	}
	// And not the reverse of how they were appended, which is what the missing
	// tiebreak produced.
	reversed := slices.Clone(want)
	slices.Reverse(reversed)
	if cmp.Diff(reversed, first) == "" {
		t.Errorf("tied events came back in reverse insertion order:\n%v", first)
	}
}
